LogLevel warn

Listen *:631
# domain socket: lets root in the container run lpadmin without a password
Listen /run/cups/cups.sock

Browsing On
BrowseLocalProtocols dnssd

DefaultAuthType Basic

WebInterface Yes

<Location />
  Order allow,deny
  Allow all
</Location>

<Location /admin>
  AuthType Default
  Require valid-user
  Order allow,deny
  Allow all
</Location>

<Location /admin/conf>
  AuthType Default
  Require valid-user
</Location>
